### ISSUE TITLE
Negative year dates causes parsing error

### ISSUE THREAD

**Issue by andrefurlan-db** [databricks/databricks-sql-go#67]
Databricks supports dates such as "-0100-01-01" which the standard go package cannot parse. We should find a solution for it.

**Comment by andrefurlan-db** [comment]
@aldld FYI

**Comment by aldld** [comment]
Thanks! Specifically what happens is [in `value` (rows.go)](https://github.com/databricks/databricks-sql-go/blob/main/rows.go#L473), `time.ParseInLocation` returns an error when given a date with negative year. In that case, the driver falls back to returning a `string` instead of a `time.Time` value.

**Comment by aldld** [comment]
Based on my search, I found this [stackoverflow post](https://stackoverflow.com/questions/51578482/parsing-dates-with-negative-year-in-go) where someone tried to build a workaround for a similar problem. Essentially, Go's `time.Time` type does appear to support negative dates; however, `time.Parse(InLocation)` doesn't know how to handle them.

(Here's a [similar bug report](https://github.com/golang/go/issues/4556) for the Go standard library issue that was marked as wontfix)
